### ISSUE TITLE
bedGraph2bigwig function 

### ISSUE THREAD

**Issue by Shicheng-Guo** [biocoder/Perl-for-Bioinformatics#6]
it would be nice if we have a perl function to transfer bedgraph to bigwig, what do you think about it?

**Comment by biocoder** [comment]
You can use `bedGraphToBigWig` tool for that. Are you having trouble using it?

**Comment by Shicheng-Guo** [comment]
Yes. too many bugs in bedGraphToBigWig including it requiring the column must be 4 and the sorting method must be sort -k1,1 -k2,2

Do you think it would be very difficult to provide a perl script for the transformation from bedgraph to bigwig?

**Comment by biocoder** [comment]
Can you send me the file and the command you used to generate BigWig file?

**Comment by Shicheng-Guo** [comment]
Sure. 

Dropbox share link: 
https://www.dropbox.com/s/8zfakh9hnp6a09s/Testdata.bedGraph?dl=0

I use the following command to pre-process the input file and then run bedGraphToBigWig 

(head -n 1 Testdata.bedGraph && tail -n +2 Testdata.bedGraph | sort -k1,1 -k2,2n | awk '{print $1,$2,$3,$4}' OFS="\t" )  > Testdata.sort.bedGraph

bedGraphToBigWig Testdata.sort.bedGraph hg19.chrom.sizes  Testdata.bw

hg19.chrom.sizes was get from fetchChromSizes command as the following:

 fetchChromSizes hg19 > hg19.chrom.sizes

fetchChromSizes was downloaded from here: 
http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/fetchChromSizes

Thanks so much for the perl script for bedGraphToBigWig

**Comment by biocoder** [comment]
Instead of trying to reinvent the wheel, did you try it this way:

`cut -f1,2,3,4 Testdata.bedGraph > Testdata.mod.bg; bedGraphToBigWig Testdata.mod.bg chrom.sizes Testdata.bw`
