### ISSUE TITLE
Installing Issue - Mac OSX

### ISSUE THREAD

**Issue by atompkins101** [biocoder/Perl-for-Bioinformatics#8]
Got this while attempting to install. 

Test Summary Report
-------------------
t/live-https.t       (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 6 tests but ran 0.
Files=6, Tests=98, 37 wallclock secs ( 0.04 usr  0.02 sys +  0.54 cusr  0.08 csys =  0.68 CPU)
Result: FAIL
Failed 1/6 test programs. 0/98 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Net::HTTP failed. See /Users/andrewtompkins/.cpanm/work/1507610394.77041/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Installed version (6.06) of Net::HTTP is not in range '6.07'
-> FAIL Bailing out the installation for libwww-perl-6.27.

**Comment by biocoder** [comment]
Hi atom,

Do you have the latest Xcode command line tools installed? Can you upload the complete log file of the installation? I would like to see the actual point of failure.

Cheers.

**Comment by biocoder** [comment]
Closing the issue since no more details are available to debug.
